# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
default_platform(:android)

platform :android do

desc "Lane for distributing the app using VS App Center"
lane :distributeDebug do
    gradle(task: "app:bundleDebug")
    appcenter_upload(
        api_token: ENV["APP_CENTER_DEBUG_TOKEN"],
        owner_name: ENV["APP_CENTER_OWNER"],
        owner_type: "user", # Default is user - set to organization for appcenter organizations
        app_name: ENV["APP_CENTER_APP_NAME_DEBUG"],
        notify_testers: false
    )
end
desc "Lane for distributing the app using VS App Center"
lane :distributeRelease do
    gradle(task: "app:bundleRelease")
    appcenter_upload(
        api_token: ENV["APP_CENTER_RELEASE_TOKEN"],
        owner_name: ENV["APP_CENTER_OWNER"],
        owner_type: "user", # Default is user - set to organization for appcenter organizations
        app_name: ENV["APP_CENTER_APP_NAME_RELEASE"],
        notify_testers: false
    )
end
desc "Lane for distributing the app using VS App Center"
lane :distributePreRelease do
    gradle(task: "app:bundlePre_release")
    appcenter_upload(
        api_token: ENV["APP_CENTER_PRE_RELEASE_TOKEN"],
        owner_name: ENV["APP_CENTER_OWNER"],
        owner_type: "user", # Default is user - set to organization for appcenter organizations
        app_name: ENV["APP_CENTER_APP_NAME_PRE_RELEASE"],
        notify_testers: false
    )
end

end
