name: Pre Release Android Workflow
"on":
  push:
    branches:
      - "pre_release/*"

jobs:
  Android_workflow:
    runs-on: macos-latest # The emulator only runs on macos, since it's the only os with HAXM enabled.
    strategy:
      matrix:
        api-level: [29] # Between api's 15 and 29
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Decode API keys
        run: echo -n "$G_SERVICES" | base64 -d > $G_SERVICES_FILE
        env: 
          G_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
          G_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_JSON_FILE }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Emulator cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(./gradlew -q printVersionName)"
        id: android_version

      - name: Get version
        run: |
          echo "VERSION_NAME=${{ steps.android_version.outputs.VERSION_NAME }}" >> $GITHUB_ENV 

      - name: Verify version
        run: |
          if [ -n "$VERSION_NAME" ]; then
            echo "Version verified, $VERSION_NAME will be used."
          else 
            echo "Version not verified."
            exit 1
          fi
          
      - name: Create emulator and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Run unit tests
        run: ./gradlew test

      - name: Deploy to app center
        run: fastlane distributePre_release
        env:
          ABB_FILE_PATH_DEBUG: ${{ secrets.ABB_FILE_PATH_PRE_RELEASE }}
          APP_CENTER_APP_NAME_DEBUG: ${{ secrets.APP_CENTER_APP_NAME_PRE_RELEASE }}
          APP_CENTER_OWNER: ${{ secrets.APP_CENTER_OWNER }}
          APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
