name: Release tagging Workflow
"on":
  push:
    branches:
      - "release/*"

jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag it
        shell: bash {0}
        run: |
          set +x

          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 || git rev-parse --abbrev-ref HEAD)

          # Extract the version parts
          IFS='.' read -ra version_parts <<< "$latest_tag"

          # Increment the last part
          ((version_parts[3]++))

          # Create the new version
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.${version_parts[3]}"

          # Create the new tag
          git tag "release/$new_version"

          # Push the new tag to GitLab
          git push origin "release/$new_version"
