name: Release tagging Workflow
"on":
  push:
    branches:
      - "release/*"

jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag it
        run: |
          # Get the tag of the previous commit
          latest_tag=$(git tag --points-at $(git rev-parse HEAD~1))

          # If the tag is empty, then get the branch name
          if [ -z "$latest_tag" ]; then
            latest_tag=$(git rev-parse --abbrev-ref HEAD)
          fi

          # Extract the version parts
          IFS='.' read -ra version_parts <<< "$latest_tag"

          # If the last part is empty then set it to 0
          if [ -z "${version_parts[3]}" ]; then
            version_parts[3]=0
          else 
            # Increment the last part
            ((version_parts[3]++))
          fi

          # Create the new version
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.${version_parts[3]}"

          # Create the new tag
          git tag "$new_version"

          # Push the new tag to GitLab
          git push origin "$new_version"
